import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
<<<<<<< HEAD
  title: 'NiArvana',
  description: 'NiArvana',
=======
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> 482d2dba8520d0692c2275a5ef6b384ed4279939
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
